### ISSUE TITLE
Choose branch

### ISSUE THREAD

**Issue by Fjsmoreira** [davidfowl/Micronetes#21]
First of all, Thank for this @davidfowl ! Such a great thing to have.

Was wondering that maybe a nice addition could be added support to choose the branch that is used and build it.

**Comment by davidfowl** [comment]
> Was wondering that maybe a nice addition could be added support to choose the branch that is used and build it.

Can you clarify? What do you mean what branch to build?

**Comment by Fjsmoreira** [comment]
A better name for it would be “add git support “ a simple configuration in the yaml file that we could specify that it would start from, for example, the branch “develop” and if the project was currently not in that branch it would not start or give a warning .

**Comment by davidfowl** [comment]
I'm confused as to what it would do. You specify what project to run. I'm not sure where git support or branch support comes in.

**Comment by Fjsmoreira** [comment]
It would let you know that the version of the project that I’m running might not be the exact one I’m looking for . In my case I would like it to run the project from my Development/master branch only. Having a warning saying what’s the branch the project currently is could be a nice addition .This would give me a piece of mind that I’m running the right project. Or maybe just a bit overkill ! 🙂

**Comment by jzabroski** [comment]
I get these types of requests in my project too and I just politely explain that I'm not implementing features of a version control system, and close the issue. 

Fernando, just check in the yaml file to source control. Edit it if your branches correspond to environments, such as gold copy data for a previous release being different from current release gold copy due to data structure differences.

**Comment by Fjsmoreira** [comment]
Fair enough and makes sense!
@jzabroski thanks for the tip!
