### ISSUE TITLE
Dapr integration for development

### ISSUE THREAD

**Issue by davidfowl** [davidfowl/Micronetes#3]
There should be a way to specify that the orchestrator should launch [dapr](https://dapr.io/) and it would appropriately wire up all of the ports and app name to make it work.

**Comment by luisgizirian** [comment]
Perhaps dropping m8s' SDK in favor of DAPR might be something to consider given:
* DAPR has a sidecar nature which doesn't force a strict dependency (unless you optionally opt-in for its SDK)
* less conflict surface for coders (i.e. [m8s sample apps](https://github.com/davidfowl/Micronetes/tree/master/samples), that are tied to m8s' SDK, fail to build into Linux - see #13 as same root cause-)
* m8s looks more like a convenient development tool (even useful for intermediate environments i'd argue). Not sure if'd rather go into production with DAPR instead (figuratively speaking as neither projects is nearly there yet)

Does these make sense?

**Comment by davidfowl** [comment]
Not really I think it’s orthogonal. m8s is a bunch of things but at the core the ability to launch several projects at once. If nothing else the ability to launch of coordinate multiple applications is useful and can be used alongside Dapr.

Dapr applications rely on the sidecar, whether the sdk is used or not. m8s applications aren’t tied to the sdk, but the sdk adds some nice APIs on top of low level conventions (like injecting env variable s with a specific name).

I haven’t figured out the non development time story yet but stay tuned 😬

**Comment by davidfowl** [comment]
Oh wait, you mean the dapr SDK specifically. I misread that. I need to think about it before deciding. I did think about implementing the protocol for some things (like pubsub) as an experiment over the existing abstractions.

**Comment by luisgizirian** [comment]
The beauty of m8s, resides in its CLI. 

Back to DAPR; application business bindings could be channeled through it. That's why I'm wondering if a public m8s SDK might be a sign of covering too much.

Thinking out loud, maybe DAPR and m8s, shouldn't relate. Leaving to the business app developer to use them both if he sees fit.

**Comment by jzabroski** [comment]
What's a "sidecar architecture" in this context?  It sounds super intelligent but I couldn't grasp what that means here.  Microsoft has a "[sidecar pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar)" in their Azure Architecture docs, but for me, that's just what API Gateways/API as a Service provides.

Is the actual sidecar idea to have an architecture where, unlike Docker, not every container is tied to a single docker daemon?  If so, can't people just say that... or is it too controversial to say Docker is a prototype that made its way into thousands if not millions of projects.

DAPR seems like Microsoft's answer to Kong/Kuma.

m8s seems to be a nicer development story alternative to going from dockerfile to docker-compose to docker-swarm, or equivalent kubernetes stack (which is more widely available).  Whether you provide cross-cutting concerns like logging, authentication, etc. as part of some "distributed runtime" doesn't matter.  Distributed runtime is just computer science talk for abstracting away your infrastructure so you don't write lots of zero value add code that a vendor is better off offering, both from security and standards perspective.

**Comment by davidfowl** [comment]
See https://github.com/dotnet/tye
